[project]
name = "ssa-telebot"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.1.0",
    "python-telegram-bot>=22.1",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
]
